// <auto-generated />
using System;
using DiarioDeSintomas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiarioDeSintomas.Migrations
{
    [DbContext(typeof(DiarioContext))]
    [Migration("20250620163659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DiarioDeSintomas.Models.DiarioSintoma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlimentacaoHidratacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Atividade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duracao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Medicamentos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutrosSintomas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PressaoArterial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sintoma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiarioSintomas");
                });
#pragma warning restore 612, 618
        }
    }
}
